###################################################################################
### logging(logback)
###################################################################################
logging:
  config: classpath:logback.xml
  level:
    _org.springframework: warn
    org.springframework: warn
    org.springframework.jdbc.datasource.DataSourceTransactionManager: info
    org.springframework.beans.factory: warn
    org.hibernate.validator: warn
    org.clever: debug

###################################################################################
### Web服务器配置
###################################################################################
server:
  port: 18081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: false

###################################################################################
### Spring配置
###################################################################################
spring:
  profiles.active: dev
  application.name: hot-reload-spring-demo
  aop.proxy-target-class: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: 'data/temp'
  mvc:
    converters:
      preferred-json-mapper: jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  web:
    resources:
      static-locations:
        - 'classpath:/META-INF/resources/'
        - 'classpath:/resources/'
        - 'classpath:/static/'
        - 'classpath:/public/'
      chain:
        cache: false
        compressed: true

###################################################################################
### clever
###################################################################################
clever:
  hot-reload:
    dev-mode: true
    root-paths: [ './cleve-hot-reload-spring-demo/src/main/groovy' ]
    http-route-modules:
      - 'org.clever.hot.reload.spring.demo.HttpRouteDemo'